name: .NET

on:
  push:
    branches: [ main , master]
  pull_request:
    branches: [ main , master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x 
      - name: Install antlr4
        run: |
          sudo apt-get update -y
          sudo apt-get install -y antlr4
      - name: Generate lexer
        working-directory: ./pascal-lexer/antlr
        run: antlr4 -Dlanguage=CSharp PascalLexer.g4
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
